### ISSUE TITLE
Unable to connect VPS with Ubuntu 18 Digital Ocean 

### ISSUE THREAD

**Issue by kakdesanket** [bonino97/LemonBooster-v2#8]
PM2      | App [Index:0] exited with code [1] via signal [SIGINT]
PM2      | App [Index:0] starting in -fork mode-
PM2      | App [Index:0] online
0|Index  | { Error: Cannot find module 'socket.io'
0|Index  |     at Function.Module._resolveFilename (module.js:547:15)
0|Index  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|Index  |     at require (internal/module.js:11:18)
0|Index  |     at Object.<anonymous> (/root/tools/LemonBooster-v2/API-LemonBooster-v2/Index.js:3:18)
0|Index  |     at Module._compile (module.js:652:30)
0|Index  |     at Object.Module._extensions..js (module.js:663:10)
0|Index  |     at Module.load (module.js:565:32)
0|Index  |     at tryModuleLoad (module.js:505:12)
0|Index  |     at Function.Module._load (module.js:497:3)
0|Index  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerForkLegacy.js:28:21) code: 'MODULE_NOT_FOUND' }
PM2      | App [Index:0] exited with code [1] via signal [SIGINT]
PM2      | App [Index:0] starting in -fork mode-
PM2      | App [Index:0] online

**Comment by kakdesanket** [comment]
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        |     at Object.God.logAndGenerateError (/usr/local/lib/node_modules/pm2/lib/God/Methods.js:34:15)
PM2        |     at /usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:384:30
PM2        |     at Object.God.stopProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:306:14)
PM2        |     at God.deleteProcessId (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:383:9)
PM2        |     at Server.onmessage (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon-rpc/lib/server.js:104:6)
PM2        |     at emitTwo (events.js:126:13)
PM2        |     at RepSocket.emit (events.js:214:7)
PM2        |     at Parser.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/rep.js:51:15)
PM2        |     at emitOne (events.js:116:13)
PM2        |     at Parser.emit (events.js:211:7)
PM2        | 2021-03-14T21:13:17: PM2 log: App [Index:0] starting in -fork mode-
PM2        | 2021-03-14T21:13:17: PM2 log: App [Index:0] online
PM2        | 2021-03-14T21:13:18: PM2 log: App [Index:0] exited with code [1] via signal [SIGINT]
PM2        | 2021-03-14T21:13:18: PM2 log: App [Index:0] starting in -fork mode-
PM2        | 2021-03-14T21:13:18: PM2 log: App [Index:0] online

/root/.pm2/logs/Index-out.log last 15 lines:
/root/.pm2/logs/Index-error.log last 15 lines:
0|Index    | { Error: Cannot find module 'socket.io'
0|Index    |     at Function.Module._resolveFilename (module.js:547:15)
0|Index    |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|Index    |     at require (internal/module.js:11:18)
0|Index    |     at Object.<anonymous> (/root/tools/LemonBooster-v2/API-LemonBooster-v2/Index.js:3:18)
0|Index    |     at Module._compile (module.js:652:30)
0|Index    |     at Object.Module._extensions..js (module.js:663:10)
0|Index    |     at Module.load (module.js:565:32)
0|Index    |     at tryModuleLoad (module.js:505:12)
0|Index    |     at Function.Module._load (module.js:497:3)
0|Index    |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerForkLegacy.js:28:21) code: 'MODULE_NOT_FOUND' }

0|Index  | { Error: Cannot find module 'socket.io'
0|Index  |     at Function.Module._resolveFilename (module.js:547:15)
0|Index  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|Index  |     at require (internal/module.js:11:18)
0|Index  |     at Object.<anonymous> (/root/tools/LemonBooster-v2/API-LemonBooster-v2/Index.js:3:18)
0|Index  |     at Module._compile (module.js:652:30)
0|Index  |     at Object.Module._extensions..js (module.js:663:10)
0|Index  |     at Module.load (module.js:565:32)
0|Index  |     at tryModuleLoad (module.js:505:12)
0|Index  |     at Function.Module._load (module.js:497:3)
0|Index  |     at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerForkLegacy.js:28:21) code: 'MODULE_NOT_FOUND' }
